[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_lib = { git = "https://github.com/Moreliaa/aoc_lib", version = "0.1.0" }
fancy-regex = "0.12.0"
itertools = "0.12.0"
num = "0.4.1"